### ISSUE TITLE
Realtime Results/Visualization

### ISSUE THREAD

**Issue by chrisuzuki62** [slamcore/semlaps#3]
Hi,

I am very fascinated by your impressive work and presentation at ICRA 2024.
I decided to test out your repo and was wondering how I can get realtime results and visualization similar to how you show in your demo video and what setup/hardware is required to get them.

Thanks,
Chris

**Comment by jacek-slamcore** [comment]
Dear Chris,
unfortunatelly we cannot support your request regarding the visualization.
Best regards,
Jacek
